//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [Display(Name = "كود  " )]
        public int ID { get; set; }
        [Display(Name = " الطالب ")]

        public string StuderntName { get; set; }
        [Display(Name = "الهاتف  ")]

        public Nullable<int> Student_Phone { get; set; }
        [Display(Name = "السن")]

        public Nullable<int> Student_age { get; set; }
        [Display(Name = "العنوان ")]

        public string Student_address { get; set; }
        public Nullable<bool> IS_Deleted { get; set; }
        public Nullable<System.DateTime> Deleted_On { get; set; }
    }
}
